return {
  -- Theme plugins (lazy-loaded; lazy.nvim auto-loads on ColorSchemePre)
  {
    "ellisonleao/gruvbox.nvim",
    lazy = true,
    opts = {
      terminal_colors = true,
      undercurl = true,
      underline = true,
      bold = true,
      italic = {
        strings = true,
        emphasis = true,
        comments = true,
        operators = false,
        folds = true,
      },
      strikethrough = true,
      invert_selection = false,
      invert_signs = false,
      invert_tabline = false,
      invert_intend_guides = false,
      inverse = true,
      contrast = "",
      dim_inactive = false,
      transparent_mode = false,
    },
    config = function(_, opts)
      require("gruvbox").setup(opts)
    end,
  },
  { "shaunsingh/nord.nvim", lazy = true },
  {
    "catppuccin/nvim",
    name = "catppuccin",
    lazy = true,
    opts = { flavour = "mocha" },
  },
  -- Theme loader: reads ~/.config/theme/current (generated by Nix)
  {
    "theme-loader",
    virtual = true,
    lazy = false,
    priority = 1000,
    config = function()
      local theme = "gruvbox"
      local f = io.open(os.getenv("HOME") .. "/.config/theme/current", "r")
      if f then
        local line = f:read("*l")
        if line and line ~= "" then
          theme = vim.trim(line)
        end
        f:close()
      end
      vim.cmd.colorscheme(theme)
    end,
  },
}
